on:
  pull_request:
    types: [ labeled ]

jobs:
  repo_search_replace:
    if: ${{ github.event.label.name == 'run_search_replace' }}
    runs-on: ubuntu-latest
    name: test run for repo file search & replace Action
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3
      - name: Search & Replace
        uses: actions/repo-search-replace@v2'
        description: 'search repo files matching the file_pattern input, and then perform a search & replace'
        with:
          file_pattern: '*.python'
          search_string: 'find_me'
          replace_string: 'replaced!'