on: [push]

jobs:
  repo_search_replace:
    runs-on: ubuntu-latest
    name: test run for repo file search & replace Action
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Search & Replace
        uses: ./
        id: repo-search-replace
        with:
          file_pattern: '*.python'
          search_string: 'find_me'
          replace_string: 'replaced!'